### ISSUE TITLE
device is not working

### ISSUE THREAD

**Issue by brianbaloch** [Emotiv/community-sdk#125]
I know very well about EMOTIV EPOC software. but my device is not working properly. After opening emotiv control panel and inserting USB in PC. I placed the headset on user. But device all electrodes switched off in few seconds. please help me. device two electrode remains on as red for few seconds, but they switched off in few seconds as place headset on user.

**Comment by brianbaloch** [comment]
please help me. I am frustrated due this device. I also used lot of given liquid on electrodes, but doesn't work. please help urgently

**Comment by hoangphamemotiv** [comment]
Hi @brianbaloch .
 We will check your issue now. 

Thanks. ^^!

**Comment by duytan90** [comment]
Hey @brianbaloch, I guess it because of the connection range, what is the distance between the headset and the USB? Please try to keep it under 1 meter if possible while placing it on user's head.

**Comment by brianbaloch** [comment]
Dear It is less than 1 meter.

**Comment by duytan90** [comment]
Hi @brianbaloch, since this issue belongs to hardware, please send us a ticket for better assistance and convenient. You could email us at hello@emotiv.com and give us as much detail as possible.

**Comment by brianbaloch** [comment]
I am fed up and frustrated because of your device. I can simply say it is
not working even the distance is less than 1 meter.

1. USB connects with headset sucessfuly. but as i touch any sensor to
change it to green then it loses connection and then it doesn't work.

**Comment by brianbaloch** [comment]
Device is not working . We have installed the required software. When
we place the device on user head. it's electrode switched off within
20 seconds. It is really frustrating for we researcher to deal with
your worst device. We were not expecting such worst device from you.
We know everything about software and all the processing of EEG data.
but because of your device , we couldn't perform the experiment. We
inserted USB in PC. USB established the connection with the headset .
When we try to correct the electrode position or press them so that we
get the green (good) signal. your headset lost connection in few
seconds. please help us. we are really very much frustrated because of
your device. please help us in removing the fault. below is the
information of the EMOTIV device which we ordered from you.

Non-profit/education license
order ID : 26016
Keyorder : 190240160
Serial : 7b76f13c797f4fb35aecb9e8a494ad34

**Comment by duytan90** [comment]
We would like you to try electrical bench test:

Thoroughly soak each sensor, then turn on the headset and get a connection.
Grasp one reference sensor with one hand, and the other reference sensor with the other hand. Pressing your thumbs against the sensors should work well. 
Now touch one or more of the other sensors. Each one should light up a second or two after you touch it. This requires a little dexterity, but it's not too difficult. 
Next touch the suspect sensor. If it does not light up, and the same sensor location does not light up even if you swap in other sensors known to be working, please let us know. There may be a broken internal wire. If you ever see that sensor light up even to red, the wiring is ok and there is some other issue.

Another thing is the connection issue with the dongle, it is usually caused by where your USB port is located on your machine. Frequently the Bluetooth or Wireless antenna is somewhere nearby, and unfortunately this can swamp the signal from the headset. Try a USB extension cable - position the dongle away from other radio sources and in clear line of sight to the headset.

If the problem still remains, please email us at **hello@emotiv.com** with a screenshot of your software running while connecting with your headset so that we can take a look and better assist. Thanks!

**Comment by brianbaloch** [comment]
now it is working. As i kept it whole night on charge. used USB connector.
But it's still one electrode is not working. please help me

**Comment by duytan90** [comment]
Please try switch that electrode with another one, add few more extra drops of liquid to see if it work.
