### ISSUE TITLE
Can't run java example!!!

### ISSUE THREAD

**Issue by thientvse** [Emotiv/community-sdk#140]
Hello Emotiv !
I have issue when running java example :

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'edk': Native library (win32-x86-64/edk.dll) not found in resource path ([file:/D:/Java/community-sdk-master/examples/Java/bin/, file:/D:/Java/community-sdk-master/lib/java/jna.jar, file:/D:/Java/community-sdk-master/include/java/])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
	at com.emotiv.Iedk.Edk.<clinit>(Edk.java:13)
	at com.emotiv.examples.EmoStateLogger.EmoStateLogger.main(EmoStateLogger.java:10)`

I am working on win7 ultimate  64bit, eclipse Version: Mars Release (4.5.0).
Could you please help me? 
Thank you very much!

**Comment by RuVT** [comment]
`Unable to load library 'edk': Native library (win32-x86-64/edk.dll) not found in resource path ([file:/D:/Java/community-sdk-master/examples/Java/bin/, file:/D:/Java/community-sdk-master/lib/java/jna.jar])`

There's the answer, just copy the edk.dll library inside one of the two directories above and try to compile again.

**Comment by hoangphamemotiv** [comment]
thank @RuVT . ^^!

**Comment by SPineapple** [comment]
_**Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'edk': Native library (darwin/libedk.dylib) not found in resource path ([file:/Users/mac/Desktop/NEWHERE/EmotivJavaExamples/bin/, file:/Users/mac/Desktop/community-sdk-3.5.0-WIN-MAC/include/java/, file:/Users/mac/Desktop/community-sdk-3.5.0-WIN-MAC/lib/java/jna.jar])**_ 

And what about this? I'm using Eclipse Oxygen and running it on MAC. 
I don't know what file exactly to copy? edk.dll won't work because I tried. and I can't find where libedk.dylib is ?

**Comment by CharlesYZhu** [comment]
I ran into the same error above. I got it to work by putting the full URL to the directory the edk.dll is located in the PATH environment variable, instead of just "../../bin/win64". I didn't need to copy the edk.dll into another directory.
