### ISSUE TITLE
Emotive Insight Javascript integration

### ISSUE THREAD

**Issue by jlmartinezInclusite** [Emotiv/community-sdk#160]
Hi,
how could I integrate a javascript application with Emotiv Insight? I saw the cPanel web application at https://cpanel.emotivinsight.com/BTLE/ but it is no longer working.

Where could I find a web application example and javascript code? I cannot find it in the repo.
Thanks so much in advance.

**Comment by manhtien2607** [comment]
Hi

We are not continue support Cpanel website and Emotiv browser plugin because this technology is base on NPAPI which will be removed from almost browser due to security issue. Chrome is the first browser totally gets rid of it. But there will be a replacement for implementing web app with Emotiv headsets soon, please keep watching our github page for information. Thanks and best regards

**Comment by inclusite** [comment]
Thanks so much for your response.
Could you please provide me with an estimated release date?
Thanks a million.
