### ISSUE TITLE
MentalCommand Android

### ISSUE THREAD

**Issue by Cballini** [Emotiv/community-sdk#213]
We are french students trying to implement the emotiv SDK into a game but we can't manage to make the android example "MentalCommand" work. (We can't find when the headset is connectiong via Bluetooth).
Can you please help us ? Thanks
We are on a Xperia XA, Android 6.0, API 25.

**Comment by tungntEmotiv** [comment]
Hi @Cballini 
Thanks for your question.
I assume that the issue occurred because your headset was paired through bluetooth settings of a certain mobile before -> can't find the headset when you run the app.
You can follow below steps:
1) If the headset has been paired with mobile before through bluetooth setting -> un-pair 
2) turn on bluetooth
3) turn on location (from Android 6.0 , need turn on location)
4) Run the app(example) again 

Note: If the app require  grant permissions. user have to accept

**Comment by Cballini** [comment]
Thanks for your reply.
I wanted to try this but I have another problem. Android Studio can't find "libbedk.so".
Do you know how to solve this problem ?

**Comment by hoangphamemotiv** [comment]
SDK v3.5.1 supported Android
https://github.com/Emotiv/community-sdk/releases/tag/v3.5.1-WIN-MAC-ANDROID

you can check latest examples. thanks. ^^!
