### ISSUE TITLE
EC_LoadUserProfile returns 1084

### ISSUE THREAD

**Issue by path77** [Emotiv/community-sdk#220]
I am trying out the SavingAndLoadingProfileCloud.py SDK example. I have put my emotiv username and password into the script and the login works fine. I have used the Emotiv Xavier Controlpanel to create two profiles. EC_GetAllProfileName correctly returns a profile count of 2. EC_ProfileIDAtIndex returns a valid profile id for my profile name. But then EC_LoadUserProfile always returns 1084. Can’t find that error code in the SDK. What does it mean? I am running this on a Raspberry PI 3 model B (armv7l) with Raspbian Jessie 8.0.

And no, my profile names do NOT contain any unicode characters.

**Comment by tungntEmotiv** [comment]
Hi @path77 

Sorry for the late reply. Yes the value is not included in error code because is libcurl error codes (CURLE_SSL_CACERT (60)). Actually we or with 0x400 before returning the value. We use libcurl to send request to EmotivCloud. And The cURL libraries are typically configured to verify the SSL certificates and refuse the connection if this verification fails.
What is your sdk version ? and how many time did you get this issue? I am sorry.
