### ISSUE TITLE
Java SDK only recognizing Neutral and Push Mental Commands 

### ISSUE THREAD

**Issue by nlizardo77** [Emotiv/community-sdk#239]
Hi,

I've been training the mental commands with the Emotiv Xavier ControlPanel application for Mac OS X, and then run a Java Program to try and detect the different mental commands.

Inside a loop in my code, I check the mental action like so:

`int mentalAction = EmoState.INSTANCE.IS_MentalCommandGetCurrentAction(eState);`

It seems to correctly detect when I am thinking PUSH because `mentalAction`  becomes 2 at some points. When I think RIGHT, however, this method still returns 2. I know I'm properly thinking RIGHT because in the mental commands app within ControlPanel, I see the cube moving to the right.

Does the IS_MentalCommandGetCurrentAction return anything other than 1 or 2 to represent the other Mental Commands? I assumed 1 corresponds to neutral and 2 corresponds to push. If it's supposed to return additional ints, are there any helpful tips you can give to make it detect the other mental commands?

I am using the most recent version of the community SDK for Java and am running it on Mac OS X version 10.11.6.

Thanks!

**Comment by tungntEmotiv** [comment]
Hi @nlizardo77 
The metalcommand actions are defined at header file( : https://github.com/Emotiv/community-sdk/blob/master/include/java/com/emotiv/Iedk/EmoState.java). Please see IEE_MentalCommandAction_t  class.
I have trained with 3 actions (neutral, push and right ) through CP and then load the profile by Examples -> its work well and the RIGHT action present as expected.
Could you try again? sometime the wrong value is caused by interference, make sure your headset at good contact quality.
If you have any concern, feel free contact me.
