### ISSUE TITLE
cannot run java basic examples

### ISSUE THREAD

**Issue by nirkai** [Emotiv/community-sdk#271]
Hi,
I have tried to run the basic examples in the SDK, but I get the error below: 
`Exception in thread "main" java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:390)
	at com.sun.jna.Function.invoke(Function.java:323)
	at com.sun.jna.Library$Handler.invoke(Library.java:236)
	at com.sun.proxy.$Proxy0.IEE_EngineConnect(Unknown Source)
	at com.emotiv.examples.AverageBandPowers.AverageBandPowers.main(AverageBandPowers.java:29)`

when I debug it, I found that it not find the Edk library, although I followed the guide and I think it should work. I'm not receive the error in compilation, but in run time so I suppose it know the path of the Edk and the jna.jar.
what did I do wrong?

Thanks,
Nir

**Comment by hoangphamemotiv** [comment]
Hi @nirkai 

i think you may want to read Jave examples document here: https://github.com/Emotiv/community-sdk/blob/master/doc/How%20to%20run%20Java%20examples.pdf

**Comment by nirkai** [comment]
Thank you for your answer.
The problem is i followed this guide, but anyway receive the error.

2017-11-29 12:06 GMT+02:00 Pham Hoang <notifications@github.com>:

**Comment by duytan90** [comment]
There are 4 steps:
1. Import existed Java examples.
2. Import header files from include folder.
3. Edit jna.jar file location (by default this is relative path, you can choose again then make it become absolute path)
4. Set PATH variable to correct edk.dll file bases on installed JDK version for each Java example.
If your installed JDK is 64 bit version, value field should be "..\..\bin\win64". Otherwise, value field should be "..\..\bin\win32".

After these steps, you should have these required files and use them in IntelliJ IDE if you want.
1. Examples file from community-sdk\examples_basic\Java\src\com\emotiv\examples
2. Header file - java files from community-sdk\include\java\com\emotiv\Iedk folder
3. Jna wrapper file (jna.jar) from community-sdk\lib folder.
4. C++ Library - the edk.dll files from community-sdk\bin folder.
[Java_setup_eclipse.zip](https://github.com/Emotiv/community-sdk/files/1521039/Java_setup_eclipse.zip)

**Comment by nirkai** [comment]
Thanks @duytan90 
about the first 4 steps,  i did it, because it also in your guide, but maybe i had a mistake in step 4. 
can you give me an example please for one java example, what exactly did i need to fill in the Variables field (in the Environment tab)?
(The word "PATH" or specific path?)

**Comment by duytan90** [comment]
@nirkai, It's the word "PATH" literally for Variable field, and specific path for Value field. Both IntelliJ IDEA and Eclipse have this configuration.
