### ISSUE TITLE
cortex, java, certificate authority

### ISSUE THREAD

**Issue by landret** [Emotiv/community-sdk#294]
Hi,
I  am programming a computer app using java, on windows 8.1, with JDK1.8.  When I try to connect to Cortex service using the java websocket api  (tyrus implementation), I got the following error in the ouput:

* Exception in thread “main” javax.websocket.DeploymentException: SSL handshake has failed
* Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
* Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
*  Caused by: sun.security.validator.ValidatorException: PKIX path  building failed:  sun.security.provider.certpath.SunCertPathBuilderException: unable to  find valid certification path to requested target
* Caused by: sun.security.provider.certpath.SunCertPathBuilderException

Looking at forums, a possible reason could be that java can’t recognize the root certificate authority (CA).

Could you help me with that?

Thanks very much
-- | --

**Comment by landret** [comment]
Hi guys,
Did you find a solution to that issue? By the way, is it even the good place to post this issue?

**Comment by duytan90** [comment]
@landret, this is the place, please wait for awhile.

**Comment by nguoithichkhampha** [comment]
hi @landret , for the cortex issue. You should create a ticket in this repository
https://github.com/Emotiv/cortex-example
For the temporary solution to work with Cortex on Java. You can try to setting ignore ssl. You will don't need Root CA to verify.

**Comment by elliothogg** [comment]
did you find an issue?

**Comment by landret** [comment]
what do you mean?

As recommended by Cuong Trinh Manh, I am using a temporary solution to work with Cortex on Java: I disabled the SSL certificate check.

I am still waiting for your team to find a more durable solution to this.



Le 18/02/2018 à 07:27, elliothogg [Masked] a écrit :
Preview: did you find an issue? -- You are receiving this because you
This email is forwarded from a MASKED EMAIL you created using Blur<https://dnt.abine.com/#help/faq/faq-whataremaskedemails>.
IF THIS IS SPAM, CLICK HERE TO BLOCK.<https://dnt.abine.com/#/block_email/03b83801@opayq.com/

Want to shop safely and privately online? Get Blur Premium<https://dnt.abine.com/#premium>.


did you find an issue?

**Comment by elliothogg** [comment]
Where are you trying to pull the data too? I have a solution to take the data and send it over OSC if you want it??

Also do you have PRO License?

I can’t pull Raw eeg even though I have one.

Thanks,
Elliot

Sent from my iPhone

On 20 Feb 2018, at 01:36, landret <notifications@github.com<mailto:notifications@github.com>> wrote:

what do you mean?

As recommended by Cuong Trinh Manh, I am using a temporary solution to work with Cortex on Java: I disabled the SSL certificate check.

I am still waiting for your team to find a more durable solution to this.



Le 18/02/2018 à 07:27, elliothogg [Masked] a écrit :
Preview: did you find an issue? -- You are receiving this because you
This email is forwarded from a MASKED EMAIL you created using Blur<https://dnt.abine.com/#help/faq/faq-whataremaskedemails>.
IF THIS IS SPAM, CLICK HERE TO BLOCK.<https://dnt.abine.com/#/block_email/03b83801@opayq.com/

Want to shop safely and privately online? Get Blur Premium<https://dnt.abine.com/#premium>.


did you find an issue?

**Comment by landret** [comment]
Hi Elliot, I have a standard license and I am not using raw eeg, so I can't help you on that, sorry.
