### ISSUE TITLE
The new Emotiv Cortex would automatic exit

### ISSUE THREAD

**Issue by mutd1997** [Emotiv/community-sdk#363]
i get the new Emotiv Cortex from https://www.emotiv.com/developer/ .But it would automatic exit after i insert the USB.

**Comment by bchaperon** [comment]
Hi @mutd1997 @Yogak97 
Sorry, I don't understand your issue.
Are you talking about a crash in the Cortex service? Or a crash in the CortexApp (ie the user interface) ?
If your problem is not related to the SDK or the Cortex API, then you should probably contact the [Emotiv customer support.](https://www.emotiv.com/contact-support/)

**Comment by Yogak97** [comment]
whenver i put the USB receiver,cortex UI shuts abruptly.

**Comment by bchaperon** [comment]
Hello @Yogak97 
For all problems related to the Emotiv applications (CortexUI, EmotivPRO, EmotivBCI) please contact the [Emotiv customer support.](https://www.emotiv.com/contact-support/)
Thanks.
